name: Testing Request Review

permissions:
  pull-requests: write

on:
  pull_request_review:
    types: [submitted]

jobs:
  echo_reviewState:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        run: echo ${{ github.event.review.state }}